### ISSUE TITLE
Allow for an external database

### ISSUE THREAD

**Issue by jonathanjfshaw** [wunderio/charts#9]
Currently the database values are always assumed to be coming from the mariadb valuyes. But we can allow for the possibility that these are set directly in values.drupal.env. 

We simply need to NOT automatically write the database variables from mariadb if mariadb is disabled:

```
env:
{{- if or (not (hasKey .Values.mariadb "enabled")) .Values.mariadb.enabled }}
- name: DB_USER
  value: "{{ .Values.mariadb.db.user }}"
- name: DB_NAME
  value: "{{ .Values.mariadb.db.name }}"
- name: DB_HOST
  value: {{ .Release.Name }}-mariadb
- name: DB_PASS
  valueFrom:
    secretKeyRef:
      name: {{ .Release.Name }}-mariadb
      key: mariadb-password
{{- end }}
- name: HASH_SALT
  valueFrom:
    secretKeyRef:
      name: {{ .Release.Name }}-secrets-drupal
      key: hashsalt  
```

**Comment by Jancis** [comment]
There's a way now.
```
mariadb:
  enabled: false

php:
  env:
    DB_HOST: '1.2.3.4'
    DB_NAME: 'drupal'
    DB_USER: 'drupal'
    DB_PASS: 'should-be-encrypted'
```
